Repository xournalpp/xournalpp, pull requests merged in 2019-06, with the labels that each got.

#1117 Allow "*.pdf.xopp" as a filename
  src/control/Control.cpp
  src/util/Path.cpp
  test/util/PathTest.cpp
Labels: do not merge

#1241 Let's Do CSS
  src/control/XournalMain.cpp
  src/control/XournalMain.h
  src/gui/MainWindow.cpp
  src/gui/MainWindow.h
  src/util/XojMsgBox.cpp
  ui/main.glade
  ui/xournalpp.css
Labels: do not merge

#1263 Only apply clang-format to changed lines
  azure-pipelines/clang-format-applied.yml
  azure-pipelines/format_diff_lines.pl
Labels: buildsystem, do not merge

#1283 Support CSS: Add name="name" property matching id's for all non-default id's
  ui/about.glade
  ui/exportSettings.glade
  ui/fillTransparency.glade
  ui/goto.glade
  ui/images.glade
  ui/main.glade
  ui/pageTemplate.glade
  ui/pagesize.glade
  ui/pdfpages.glade
  ui/plugin.glade
  ui/pluginEntry.glade
  ui/settings.glade
  ui/settingsButtonConfig.glade
  ui/settingsDeviceClassConfig.glade
  ui/texdialog.glade
  ui/toolbarCustomizeDialog.glade
  ui/toolbarManageDialog.glade
Labels: do not merge

#1228 Place newly created latex objects in the center of the screen/page
  src/control/LatexController.cpp
Labels: enhancement, papercut

#1289 Bugfix: The undoList of UndoRedoHandler is not cleared after calling …
  src/undo/UndoRedoHandler.cpp
Labels: bug

#1090 Implement staves for music notes #1084
  src/control/pagetype/PageTypeHandler.cpp
  src/control/settings/PageTemplateSettings.cpp
  src/control/settings/Settings.cpp
  src/control/xojfile/XojExportHandler.cpp
  src/gui/dialog/SettingsDialog.cpp
  src/model/XojPage.cpp
  src/view/background/LineBackgroundPainter.cpp
  src/view/background/LineBackgroundPainter.h
  src/view/background/LineBackgroundType.h
  src/view/background/MainBackgroundPainter.cpp
  test/control/LoadHandlerTest.cpp
  test/files/load/pages.xml
  test/files/preview-test-no-preview.unzipped.xoj
  test/files/preview-test.unzipped.xoj
  test/files/test1.unzipped.xoj
  ui/pagetemplates.ini
  ui/settings.glade
Labels: do not merge
