Repository xournalpp/xournalpp, pull requests merged in 2019-08, with the labels that each got.

#1388 correctly handle extensions when exporting
  src/control/jobs/CustomExportJob.cpp
  src/control/jobs/PdfExportJob.cpp
  src/util/Path.cpp
  src/util/Path.h
  test/util/PathTest.cpp
Labels: bug

#1238 Refactor layout & resizing routine
  src/control/Control.cpp
  src/control/zoom/ZoomControl.cpp
  src/control/zoom/ZoomControl.h
  src/gui/Layout.cpp
  src/gui/Layout.h
  src/gui/LayoutMapper.cpp
  src/gui/LayoutMapper.h
  src/gui/MainWindow.cpp
  src/gui/PageView.h
  src/gui/XournalView.cpp
  src/gui/scroll/ScrollHandlingGtk.cpp
  src/gui/widgets/XournalWidget.cpp
  src/util/hashcombine.h
Labels: Zoom, partial fix, refactoring

#1410 Add option to disable overlay scrolling
  src/control/settings/Settings.cpp
  src/control/settings/Settings.h
  src/gui/MainWindow.cpp
  src/gui/dialog/SettingsDialog.cpp
  ui/settings.glade
Labels: enhancement

#1416 fixes #1415 WIP: Adds 2 tools for pen sizes.
  src/control/Control.cpp
  src/control/ToolHandler.cpp
  src/enums/ActionType.enum.h
  src/enums/generated/ActionType.generated.cpp
  src/gui/toolbarMenubar/ToolMenuHandler.cpp
  ui/icons/hicolor/icon-theme.cache
  ui/icons/hicolor/scalable/actions/thickness_fine.svg
  ui/icons/hicolor/scalable/actions/thickness_very_fine.svg
  ui/icons/hicolor/scalable/actions/thickness_very_thick.svg
  ui/main.glade
Labels: bug, enhancement, low priority

#1392 Add .deb cpack configuration
  CMakeLists.txt
  readme/LinuxBuild.md
Labels: buildsystem
