Repository xournalpp/xournalpp, pull requests merged in 2020-12, with the labels that each got.

#2453 Fix and simplify metadata manager read
  src/control/XournalMain.cpp
  src/control/settings/MetadataManager.cpp
Labels: regression

#2536 Fix regression default tool at startup
  src/control/Control.cpp
Labels: bug, confirmed, regression

#2537 Fix segmentation fault for missing ColorToolItem
  src/gui/toolbarMenubar/ColorToolItem.cpp
Labels: bug, confirmed, regression

#2530 Take toolsize and erasertype from corresponding toolbar tool when triggered by Button
  src/control/ToolHandler.cpp
  src/control/ToolHandler.h
  src/control/settings/ButtonConfig.cpp
  src/control/settings/ButtonConfig.h
Labels: regression

#2541 Fixes zoomFitValue update hindering scrolling
  src/control/LatexController.cpp
  src/control/tools/EditSelection.cpp
  src/control/zoom/ZoomControl.cpp
  src/control/zoom/ZoomControl.h
  src/gui/Layout.cpp
  src/gui/Layout.h
  src/gui/MainWindow.cpp
  src/gui/XournalView.cpp
  src/gui/inputdevices/AbstractInputHandler.cpp
  src/gui/inputdevices/old/InputSequence.cpp
  src/gui/scroll/ScrollHandlingGtk.cpp
  src/gui/widgets/XournalWidget.cpp
Labels: blocked
