Repository xournalpp/xournalpp, pull requests merged in 2021-09, with the labels that each got.

#2704 Remove console window flash at startup on Windows
  src/CMakeLists.txt
  src/Xournalpp.cpp
  src/win32/console.cpp
  src/win32/console.h
Labels: os::windows

#3383 (minor fix) Fix typo from 'orignal' to 'original'
  src/undo/SizeUndoAction.cpp
Labels: refactoring

#3391 (Minor) Fix format specifiers to match types
  src/control/xml/SizeTAttribute.cpp
  src/gui/dialog/AboutDialog.cpp
  src/model/Document.cpp
Labels: refactoring

#3299 Release Helper Scripts
  CHANGELOG.md
  CMakeLists.txt
  debian/changelog
  desktop/com.github.xournalpp.xournalpp.appdata.xml
  readme/Releases.md
  scripts/release_helper.sh
  xournalpp-ubuntu-ppa.recipe
Labels: buildsystem

#3344 Fix a bug that makes single point stroke pressureless
  src/control/tools/StrokeHandler.cpp
  src/control/tools/StrokeHandler.h
  src/gui/inputdevices/PenInputHandler.cpp
Labels: merge proposed

#3379 Settings: Allow disabling GTK inertial touch scrolling.
  src/control/settings/Settings.cpp
  src/control/settings/Settings.h
  src/gui/MainWindow.cpp
  src/gui/dialog/SettingsDialog.cpp
  ui/settings.glade
Labels: merge proposed
