Repository xournalpp/xournalpp, pull requests merged in 2021-03, with the labels that each got.

#2885 Fix Backup on Save Mechanism
  src/control/jobs/SaveJob.cpp
Labels: regression

#2906 Fix Crash on permission failure
  src/control/jobs/BaseExportJob.cpp
Labels: Crash, priority::high

#2972 Replaced old internal SNDFILE name with puplic name, because it changed.
  src/util/audio/VorbisConsumer.cpp
  src/util/audio/VorbisProducer.cpp
Labels: Dependency Issue, difficulty::easy, os::mac, packaging, priority::high

#2955 Fix crash on scroll with sidebar preview open
  src/control/jobs/Job.cpp
  src/control/jobs/Job.h
  src/control/jobs/PreviewJob.cpp
  src/control/jobs/PreviewJob.h
  src/control/jobs/Scheduler.cpp
  src/control/jobs/Scheduler.h
  src/control/jobs/XournalScheduler.cpp
  src/control/jobs/XournalScheduler.h
Labels: refactoring
