Repository xournalpp/xournalpp, pull requests merged in 2021-11, with the labels that each got.

#3511 Add null check to device in InputEvent's handler
  AUTHORS
  src/control/XournalMain.cpp
  src/gui/TextEditor.cpp
  src/gui/inputdevices/InputContext.cpp
Labels: Input, merge proposed

#3534 Switch to FontConfig Backend for Cairo-Pango on Windows
  src/Xournalpp.cpp
Labels: merge proposed

#3476 Migrate from CPPUnit to gtest
  CMakeLists.txt
  azure-pipelines/continuous-integration.yml
  azure-pipelines/create-installers.yml
  azure-pipelines/dependencies/msys2-blob.yml
  azure-pipelines/jobs/release_ubuntu.yml
  azure-pipelines/release.yml
  azure-pipelines/steps/build_mac.yml
  azure-pipelines/steps/build_windows.yml
  azure-pipelines/steps/install_deps_ubuntu.yml
  mac-setup/build-cppunit.sh
  rpm/fedora/xournalpp.spec
  src/CMakeLists.txt
  src/xoj-preview-extractor/CMakeLists.txt
  test/CMakeLists.txt
  test/README.md
  test/SpeedTest.cpp
  test/TestMain.cpp
  test/control/LoadHandlerTest.cpp
  test/unit_tests/control/LoadHandlerTest.cpp
  test/unit_tests/util/ColorTest.cpp
  test/unit_tests/util/I18nTest.cpp
  test/unit_tests/util/ObjectIOStreamTest.cpp
  test/unit_tests/util/PathTest.cpp
  test/unit_tests/util/StringUtilsTest.cpp
  test/unit_tests/util/XojPreviewExtractorTest.cpp
  test/util/ColorTest.cpp
  test/util/I18nTest.cpp
  test/util/ObjectIOStreamTest.cpp
  test/util/PathTest.cpp
  test/util/StringUtilsTest.cpp
  test/util/XojPreviewExtractorTest.cpp
Labels: enhancement, priority::low, merge proposed

#3518 Fixing typo
  src/control/XournalMain.cpp
Labels: merge proposed

#3515 FillOpacity minor changes:
  src/control/Control.cpp
  src/gui/dialog/FillOpacityDialog.cpp
  src/gui/dialog/FillOpacityDialog.h
  ui/fillOpacity.glade
Labels: merge proposed

#3480 Improve Stroke's display in StrokeView and StrokeHandler
  src/config-debug.h.in
  src/control/tools/BaseStrokeHandler.cpp
  src/control/tools/SplineHandler.cpp
  src/control/tools/StrokeHandler.cpp
  src/control/tools/StrokeHandler.h
  src/view/DocumentView.cpp
  src/view/DocumentView.h
  src/view/StrokeView.cpp
  src/view/StrokeView.h
Labels: rendering, merge proposed

#3364 Extend Lua API to get info on tools
  plugins/Example/main.lua
Labels: merge proposed

#3563 Remove mentions of CppUnit in all READMEs
  cmake/README.md
  readme/LinuxBuild.md
  readme/WindowsBuild.md
Labels: merge proposed

#3540 Added system cursor as pen cursor option.
  src/control/settings/Settings.cpp
  src/control/settings/SettingsEnums.cpp
  src/control/settings/SettingsEnums.h
  src/gui/XournalppCursor.cpp
  src/gui/dialog/SettingsDialog.cpp
  ui/settings.glade
Labels: merge proposed

#3551 Set classic locale for PDF export link attributes
  src/control/XournalMain.cpp
  src/control/jobs/PdfExportJob.cpp
  src/pdf/base/XojCairoPdfExport.cpp
Labels: merge proposed

#3576 Prevent installation of Google test
  CMakeLists.txt
  src/CMakeLists.txt
  test/CMakeLists.txt
Labels: bug, priority::high, merge proposed

#3580 Fix failing assert #3578
  src/view/StrokeView.cpp
Labels: merge proposed

#2379 Customizable color palette using .gpl config file
  CMakeLists.txt
  src/config-dev.h.in
  src/control/XournalMain.cpp
  src/control/settings/Settings.cpp
  src/control/settings/Settings.h
  src/gui/ToolitemDragDrop.cpp
  src/gui/ToolitemDragDrop.h
  src/gui/dialog/toolbarCustomize/CustomizeableColorList.cpp
  src/gui/dialog/toolbarCustomize/CustomizeableColorList.h
  src/gui/dialog/toolbarCustomize/ToolItemDragCurrentData.cpp
  src/gui/dialog/toolbarCustomize/ToolItemDragCurrentData.h
  src/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp
  src/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.cpp
  src/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.h
  src/gui/inputdevices/InputUtils.h
  src/gui/toolbarMenubar/AbstractItem.cpp
  src/gui/toolbarMenubar/AbstractItem.h
  src/gui/toolbarMenubar/AbstractToolItem.cpp
  src/gui/toolbarMenubar/AbstractToolItem.h
  src/gui/toolbarMenubar/ColorToolItem.cpp
  src/gui/toolbarMenubar/ColorToolItem.h
  src/gui/toolbarMenubar/FontButton.cpp
  src/gui/toolbarMenubar/FontButton.h
  src/gui/toolbarMenubar/ToolButton.cpp
  src/gui/toolbarMenubar/ToolButton.h
  src/gui/toolbarMenubar/ToolMenuHandler.cpp
  src/gui/toolbarMenubar/ToolMenuHandler.h
  src/gui/toolbarMenubar/ToolPageLayer.cpp
  src/gui/toolbarMenubar/ToolPageLayer.h
  src/gui/toolbarMenubar/ToolPageSpinner.cpp
  src/gui/toolbarMenubar/ToolPageSpinner.h
  src/gui/toolbarMenubar/ToolZoomSlider.cpp
  src/gui/toolbarMenubar/ToolZoomSlider.h
  src/gui/toolbarMenubar/icon/ToolbarSeparatorImage.cpp
  src/gui/toolbarMenubar/icon/ToolbarSeparatorImage.h
  src/gui/toolbarMenubar/model/ColorPalette.cpp
  src/gui/toolbarMenubar/model/ColorPalette.h
  src/gui/toolbarMenubar/model/ToolbarColorNames.cpp
  src/gui/toolbarMenubar/model/ToolbarColorNames.h
  src/gui/toolbarMenubar/model/ToolbarEntry.cpp
  src/gui/toolbarMenubar/model/ToolbarItem.cpp
  src/gui/toolbarMenubar/model/ToolbarItem.h
  src/gui/toolbarMenubar/model/ToolbarModel.cpp
  src/util/CMakeLists.txt
  src/util/Color.h
  src/util/NamedColor.cpp
  src/util/NamedColor.h
  src/util/StringUtils.h
  src/xoj-preview-extractor/CMakeLists.txt
  test/files/palettes/bad_color_1.gpl
  test/files/palettes/bad_color_2.gpl
  test/files/palettes/bad_color_3.gpl
  test/files/palettes/broken_attribute.gpl
  test/files/palettes/default.gpl
  test/files/palettes/empty.gpl
  test/files/palettes/not_broken_attribute.gpl
  test/files/palettes/rainbow.gpl
  test/files/palettes/wrong_header.gpl
  test/unit_tests/model/ColorPaletteTest.cpp
  ui/toolbar.ini
Labels: enhancement, difficulty::medium

#3587 Change autosave dir to ~/.cache/xournalpp/autosaves
  src/core/control/Control.cpp
  src/util/PathUtil.cpp
  ui/settings.glade
Labels: merge proposed
