Repository xournalpp/xournalpp, pull requests merged in 2021-12, with the labels that each got.

#3042 Replace some GList with STL structs
  src/core/control/ClipboardHandler.cpp
  src/core/control/tools/Selection.cpp
  src/core/control/tools/Selection.h
  src/core/control/xml/XmlNode.cpp
  src/core/control/xml/XmlNode.h
  src/core/control/xml/XmlPointNode.cpp
  src/core/control/xml/XmlPointNode.h
  src/core/control/xojfile/SaveHandler.cpp
  src/core/control/xojfile/SaveHandler.h
  src/core/gui/dialog/FormatDialog.cpp
  src/core/gui/dialog/FormatDialog.h
  src/core/model/BackgroundImage.cpp
  src/core/model/BackgroundImage.h
  src/core/model/eraser/ErasableStroke.cpp
  src/core/model/eraser/ErasableStroke.h
  src/core/model/eraser/ErasableStrokePart.cpp
  src/core/model/eraser/ErasableStrokePart.h
  src/core/model/eraser/PartList.cpp
  src/core/model/eraser/PartList.h
  src/core/undo/AddUndoAction.cpp
  src/core/undo/AddUndoAction.h
  src/core/undo/DeleteUndoAction.cpp
  src/core/undo/DeleteUndoAction.h
  src/core/undo/EraseUndoAction.cpp
  src/core/undo/EraseUndoAction.h
  src/core/undo/PageLayerPosEntry.h
Labels: refactoring

#3530 Code cleanup around ShapeRecognizer
  src/core/control/Control.cpp
  src/core/control/Control.h
  src/core/control/UndoRedoController.cpp
  src/core/control/layer/LayerController.cpp
  src/core/control/shaperecognizer/ShapeRecognizer.cpp
  src/core/control/shaperecognizer/ShapeRecognizer.h
  src/core/control/shaperecognizer/ShapeRecognizerConfig.h
  src/core/control/shaperecognizer/ShapeRecognizerResult.cpp
  src/core/control/shaperecognizer/ShapeRecognizerResult.h
  src/core/control/tools/InputHandler.cpp
  src/core/control/tools/InputHandler.h
  src/core/control/tools/StrokeHandler.cpp
  src/core/control/tools/StrokeHandler.h
  src/core/gui/PageView.cpp
  src/core/gui/PageView.h
  src/core/gui/XournalView.cpp
  src/core/gui/XournalView.h
Labels: refactoring

#3652 Fix #3651 - remove pressure value on Highlighter strokes first point
  src/control/tools/InputHandler.cpp
Labels: priority::high, merge proposed

#3653 Merge release branch into master
  src/core/control/Control.cpp
  src/core/control/RecentManager.cpp
  src/core/control/tools/InputHandler.cpp
  src/core/model/Document.cpp
  src/util/PathUtil.cpp
  src/util/include/util/PathUtil.h
Labels: merge proposed
