Repository xournalpp/xournalpp, pull requests merged in 2022-10, with the labels that each got.

#4259 Improve cannot find pdflatex error in Flatpak
  src/control/latex/LatexGenerator.cpp
  src/util/Util.cpp
  src/util/Util.h
Labels: Flatpak, merge proposed

#4258 Plug leaking Stroke in StrokeHandler::strokeRecognizerDetected
  src/control/tools/StrokeHandler.cpp
Labels: merge proposed

#4264 Allow the default LaTeX text when inserting to be configurable
  src/core/control/LatexController.cpp
  src/core/control/settings/LatexSettings.h
  src/core/control/settings/Settings.cpp
  src/core/gui/dialog/LatexSettingsPanel.cpp
  ui/latexSettings.glade
Labels: LaTeX, UX, merge proposed

#4293 Hotfix: Prevent `g_object_get` segfault
  src/gui/dialog/toolbarCustomize/ToolbarDragDropHelper.cpp
Labels: merge proposed

#4292 Bind Ctrl+Shift+Z to redo
  ui/main.glade
Labels: merge proposed

#4294 Release script improvements
  scripts/release_helper.sh
Labels: merge proposed

#4299 Fix PDF toolbox stroke actions when PDF page num is not current page
  src/core/gui/PdfFloatingToolbox.cpp
Labels: merge proposed

#4302 Fix #4301
  src/core/control/Control.cpp
  src/core/control/tools/EditSelectionContents.cpp
  src/core/control/tools/InputHandler.cpp
  src/core/control/tools/StrokeHandler.cpp
  src/core/control/tools/StrokeStabilizer.cpp
  src/core/control/xojfile/LoadHandler.cpp
  src/core/control/xojfile/SaveHandler.cpp
  src/core/gui/PdfFloatingToolbox.cpp
  src/core/gui/XournalView.cpp
  src/core/model/Stroke.cpp
  src/core/model/Stroke.h
  src/core/model/eraser/ErasableStroke.cpp
  src/core/plugin/luapi_application.h
  src/core/view/ErasableStrokeView.cpp
  src/core/view/StrokeView.cpp
  src/core/view/overlays/BaseShapeOrSplineToolView.cpp
  src/core/view/overlays/BaseStrokeToolView.cpp
  test/unit_tests/model/ErasableStrokeTest.cpp
  test/unit_tests/util/ObjectIOStreamTest.cpp
Labels: merge proposed

#4317 Fix UB for BaseShapeHandler when clicking without moving
  src/core/control/tools/BaseShapeHandler.cpp
Labels: merge proposed

#4060 New Crowdin updates
  po/af_ZA.po
  po/ar.po
  po/ca.po
  po/cs.po
  po/da.po
  po/de.po
  po/el.po
  po/eo_UY.po
  po/es.po
  po/eu.po
  po/fi.po
  po/fr.po
  po/gl.po
  po/he.po
  po/hi.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/no.po
  po/pl.po
  po/pt_BR.po
  po/pt_PT.po
  po/ro.po
  po/ru.po
  po/si_LK.po
  po/sv.po
  po/th.po
  po/tr.po
  po/vi.po
  po/zh.po
  po/zh_HK.po
  po/zh_TW.po
Labels: merge proposed

#4263 Added the "Fill Opacity" feature to the available toolbar items
  src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
  ui/iconsColor-dark/hicolor/scalable/actions/xopp-pen-fill-opacity.svg
  ui/iconsLucide-dark/hicolor/scalable/actions/xopp-pen-fill-opacity.svg
  ui/iconsLucide-light/hicolor/scalable/actions/xopp-pen-fill-opacity.svg
Labels: merge proposed

#4312 Declare a default virtual destructor in XmlNode
  src/core/control/xml/XmlNode.h
Labels: merge proposed

#4315 Auto-select edited text object when switching from text- to select-tool
  src/core/control/Control.cpp
  src/core/control/Tool.cpp
  src/core/control/Tool.h
  src/core/control/ToolEnums.cpp
  src/core/control/ToolEnums.h
  src/core/control/ToolHandler.cpp
  src/core/control/ToolHandler.h
Labels: merge proposed

#4320 Fix problems when drawing an ellipse
  src/core/control/tools/EllipseHandler.cpp
Labels: merge proposed

#4347 Fix segfault when switching from text to selection tool
  src/core/control/Control.cpp
Labels: regression

#4345 Fix crash when tex generator is not found
  src/control/latex/LatexGenerator.cpp
Labels: regression, merge proposed

#4283 Minimum size for shape recognizer now customizable
  src/core/control/settings/Settings.cpp
  src/core/control/settings/Settings.h
  src/core/control/shaperecognizer/ShapeRecognizer.cpp
  src/core/control/shaperecognizer/ShapeRecognizer.h
  src/core/control/tools/StrokeHandler.cpp
  src/core/gui/dialog/SettingsDialog.cpp
  ui/settings.glade
Labels: merge proposed

#4354 Add LoadHandler::fixNullPressureValues
  src/core/control/xojfile/LoadHandler.cpp
  src/core/control/xojfile/LoadHandler.h
  src/core/model/Stroke.cpp
  src/core/model/Stroke.h
  test/files/packaged_xopp/stroke/width_recovery.xopp
  test/unit_tests/control/LoadHandlerTest.cpp
Labels: merge proposed
