Repository xournalpp/xournalpp, pull requests merged in 2022-06, with the labels that each got.

#4061 [1.1.x] ci: update Windows VM image to windows-2019
  azure-pipelines/continuous-integration.yml
  azure-pipelines/create-installers.yml
  azure-pipelines/dependencies/msys2-blob.yml
  azure-pipelines/release.yml
Labels: buildsystem

#4080 Prevent fractional translation of mask surface
  src/core/control/tools/StrokeHandler.cpp
Labels: merge proposed

#4074 Optimize TextEditor calls for rerendering
  src/gui/PageView.cpp
  src/gui/TextEditor.cpp
  src/gui/TextEditor.h
Labels: merge proposed

#2422 Add several plugin loading paths
  .clang-tidy
  src/core/gui/dialog/PluginDialog.cpp
  src/core/gui/dialog/PluginDialogEntry.cpp
  src/core/plugin/Plugin.cpp
  src/core/plugin/Plugin.h
  src/core/plugin/PluginController.cpp
  src/core/plugin/PluginController.h
  ui/pluginEntry.glade
Labels: enhancement, difficulty::easy

#4116 remove macos-launcher and simplify build-app.sh
  mac-setup/build-app.sh
  mac-setup/xournalpp.bundle
  src/CMakeLists.txt
  src/exe/Xournalpp.cpp
  src/exe/osx/setup-env.cpp
  src/exe/osx/setup-env.h
  src/util/PathUtil.cpp
Labels: merge proposed

#4121 Forward-declare XojPage in PageRef and protect headers
  src/core/audio/AudioQueue.h
  src/core/control/CrashHandlerWindows.h
  src/core/gui/ToolbarDefinitions.h
  src/core/gui/widgets/ZoomCallib.h
  src/core/gui/widgets/gtkmenutooltogglebutton.h
  src/core/model/ElementContainer.h
  src/core/model/PageRef.h
  src/core/plugin/PluginController.cpp
  src/core/plugin/luapi_application.h
  src/util/include/util/CircularBuffer.h
  test/unit_tests/control/LoadHandlerTest.cpp
Labels: merge proposed
