Repository xournalpp/xournalpp, pull requests merged in 2022-04, with the labels that each got.

#3947 Select correct tool when selecting default tool
  src/control/Control.cpp
Labels: merge proposed

#3934 3921 show the filepath in the titlebar along with the filename
  src/core/control/Control.cpp
  src/core/control/settings/Settings.cpp
  src/core/control/settings/Settings.h
  src/core/gui/dialog/SettingsDialog.cpp
  ui/settings.glade
Labels: merge proposed

#3970 Remove x and y from GtkXournal struct
  src/core/gui/inputdevices/AbstractInputHandler.cpp
  src/core/gui/inputdevices/SetsquareInputHandler.cpp
  src/core/gui/widgets/XournalWidget.cpp
  src/core/gui/widgets/XournalWidget.h
Labels: merge proposed

#3964 MacOS: fix linker flags when using MacPorts
  CMakeLists.txt
  src/xoj-preview-extractor/CMakeLists.txt
Labels: buildsystem

#3984 Fix crash when button pressed while vertical space tool active
  src/core/gui/PageView.cpp
Labels: regression
