Repository xournalpp/xournalpp, pull requests merged in 2023-03, with the labels that each got.

#4599 Default pdf-export name with wildcards
  src/core/control/jobs/BaseExportJob.cpp
  src/core/control/settings/Settings.cpp
  src/core/control/settings/Settings.h
  src/core/model/Document.cpp
  src/core/model/Document.h
  src/util/SaveNameUtils.cpp
  src/util/include/util/SaveNameUtils.h
  test/unit_tests/util/SaveNameUtilsTest.cpp
Labels: merge proposed

#4672 Fix bounding box for pressure-sensitive strokes
  src/core/model/Stroke.cpp
  src/core/model/Stroke.h
Labels: merge proposed

#4690 Fix the filename suggestions when annotating PDFs
  src/core/model/Document.cpp
Labels: merge proposed

#4665 Make visibility of eraser cursor configurable
  src/core/control/settings/Settings.cpp
  src/core/control/settings/Settings.h
  src/core/control/settings/SettingsEnums.cpp
  src/core/control/settings/SettingsEnums.h
  src/core/gui/XournalppCursor.cpp
  src/core/gui/dialog/SettingsDialog.cpp
  ui/settings.glade
Labels: merge proposed

#4698 Fix lifetime of references
  src/core/view/overlays/VerticalToolView.cpp
Labels: merge proposed

#4695 Use RAII MainWindow toolbarWidgets
  src/core/gui/MainWindow.cpp
  src/core/gui/MainWindow.h
  src/core/gui/dialog/toolbarCustomize/ToolbarDragDropHandler.cpp
  src/core/gui/dialog/toolbarCustomize/ToolbarDragDropHandler.h
Labels: merge proposed

#4705 fix png export for PDF background
  src/core/control/jobs/ImageExport.cpp
Labels: merge proposed, export

#4676 Fix StrokeStabilizer::quadraticSplineTo()'s handling of pressure values
  src/core/control/tools/StrokeStabilizer.cpp
Labels: merge proposed

#4055 scale small arrow heads by line length
  src/core/control/tools/ArrowHandler.cpp
Labels: merge proposed

#4674 Add spacer for drag&drop in toolbar customization
  src/core/gui/ToolitemDragDrop.cpp
  src/core/gui/dialog/toolbarCustomize/ToolbarAdapter.cpp
  src/core/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.cpp
  src/core/gui/dialog/toolbarCustomize/ToolbarCustomizeDialog.h
  src/core/gui/toolbarMenubar/icon/ToolbarSeparatorImage.cpp
  src/core/gui/toolbarMenubar/icon/ToolbarSeparatorImage.h
  ui/toolbarCustomizeDialog.glade
Labels: merge proposed

#4462 Add release checklist to readme/Releases.md
  readme/Releases.md
Labels: merge proposed

#4652 [luaAPI] refactor error handling
  src/core/plugin/Plugin.cpp
  src/core/plugin/luapi_application.h
Labels: plugins, merge proposed

#4671 feature: add toolbar buttons via plugins
  src/core/control/Control.cpp
  src/core/control/Control.h
  src/core/gui/MainWindow.cpp
  src/core/gui/toolbarMenubar/PluginToolButon.cpp
  src/core/gui/toolbarMenubar/PluginToolButton.h
  src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
  src/core/gui/toolbarMenubar/ToolMenuHandler.h
  src/core/plugin/Plugin.cpp
  src/core/plugin/Plugin.h
  src/core/plugin/PluginController.cpp
  src/core/plugin/PluginController.h
  src/core/plugin/luapi_application.h
Labels: plugins, merge proposed

#4715 Fix #4675 No error on save if we don't have write permission
  src/core/control/jobs/SaveJob.cpp
Labels: merge proposed

#4734 Fix dark background color of tex dialog
  src/util/Color.cpp
  src/util/include/util/Color.h
Labels: merge proposed

#4728 Ensure we can compile without plugins enabled. Fix #4726
  src/core/gui/toolbarMenubar/PluginToolButon.cpp
  src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
Labels: merge proposed

#4749 Apply include-what-you-use to headers in util/ without associated .cpp file
  src/core/control/xojfile/LoadHandler.cpp
  src/util/include/util/BasePointerIterator.h
  src/util/include/util/CircularBuffer.h
  src/util/include/util/DispatchPool.h
  src/util/include/util/GListView.h
  src/util/include/util/Interval.h
  src/util/include/util/LoopUtil.h
  src/util/include/util/PairView.h
  src/util/include/util/Rectangle.h
  src/util/include/util/SmallVector.h
  src/util/include/util/TinyVector.h
  src/util/include/util/UnionOfIntervals.h
  src/util/include/util/safe_casts.h
Labels: merge proposed

#4725 Deselect on undo/redo. Fix #4609
  src/core/control/Control.cpp
Labels: merge proposed

#4744 Don't allocate dialogs on heap
  src/core/control/Control.cpp
  src/core/control/PageBackgroundChangeController.cpp
  src/core/gui/dialog/PageTemplateDialog.cpp
Labels: merge proposed
