Repository xournalpp/xournalpp, pull requests merged in 2023-08, with the labels that each got.

#4956 Optionally Display Current Page Number on the Titlebar
  src/core/control/Control.cpp
  src/core/control/settings/Settings.cpp
  src/core/control/settings/Settings.h
  src/core/gui/dialog/SettingsDialog.cpp
  ui/settings.glade
Labels: merge proposed

#4996 Install libgtksourceview-4-dev on Azure pipelines
  azure-pipelines/release.yml
  azure-pipelines/steps/install_deps_ubuntu.yml
Labels: merge proposed

#4837 Lua api refactor stack
  src/core/plugin/luapi_application.h
Labels: merge proposed

#4528 Add plugin to fit the page size to the content/selection
  plugins/FitToContent/main.lua
  plugins/FitToContent/plugin.ini
Labels: plugins, merge proposed

#5002 Remove PageTypeFormat::Copy
  src/core/control/PageBackgroundChangeController.cpp
  src/core/control/PageBackgroundChangeController.h
  src/core/control/pagetype/PageTypeHandler.cpp
  src/core/control/pagetype/PageTypeHandler.h
  src/core/control/pagetype/PageTypeMenu.cpp
  src/core/control/pagetype/PageTypeMenu.h
  src/core/control/settings/PageTemplateSettings.cpp
  src/core/control/settings/PageTemplateSettings.h
  src/core/control/xojfile/LoadHandler.cpp
  src/core/control/xojfile/SaveHandler.cpp
  src/core/gui/dialog/PageTemplateDialog.cpp
  src/core/gui/dialog/PageTemplateDialog.h
  src/core/model/PageType.cpp
  src/core/model/PageType.h
  src/core/view/background/BackgroundView.cpp
Labels: merge proposed

#5019 Consistently set ENABLE_PLUGINS
  CMakeLists.txt
  src/core/gui/menus/menubar/Menubar.cpp
  src/core/gui/menus/menubar/Menubar.h
  src/core/gui/toolbarMenubar/ToolMenuHandler.cpp
  src/core/plugin/Plugin.cpp
  src/core/plugin/PluginController.cpp
Labels: buildsystem, papercut, merge proposed

#4871 Modifying the Bug Report, and Feature Request templates to make them more user Friendly
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/input-related-bug-report.md
Labels: merge proposed

#5032 Make bugreports use bug report template
  cmake/include/GitRepo.cmake
Labels: merge proposed

#5022 Add age filter on crash logs reported at startup
  src/core/control/CrashHandlerUnix.h
  src/core/control/XournalMain.cpp
Labels: merge proposed

#5028 Fix negative pressures #5025
  src/core/control/settings/Settings.cpp
  src/core/gui/inputdevices/PenInputHandler.cpp
  src/core/gui/inputdevices/PenInputHandler.h
  ui/settings.glade
Labels: merge proposed

#5030 Refactor sidebar to use vector+iterator instead of list+pointer
  src/core/gui/sidebar/Sidebar.cpp
  src/core/gui/sidebar/Sidebar.h
Labels: enhancement, refactoring, merge proposed

#5056 Update package description
  README.md
  debian/control
  desktop/com.github.xournalpp.xournalpp.appdata.xml
  package_description
Labels: merge proposed

#5055 Update changelog in preparation for 1.2.1 release
  CHANGELOG.md
Labels: merge proposed
